{% set name = "ribasim" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cbcce049ef8f88e570932e980e0add5f1048c646a396f60279fa7ca1f85fe744

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.9
    - setuptools >=61
    - pip
  run:
    - python >=3.9
    - geopandas
    - matplotlib-base
    - pandas <2.1
    - pandera !=0.16.0
    - pyarrow
    - pydantic =1
    - pyogrio
    - shapely >=2.0
    - tomli
    - tomli-w

test:
  imports:
    - ribasim
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://deltares.github.io/Ribasim/
  summary: Pre- and post-process Ribasim
  description: |
    The Ribasim Python package (named `ribasim`) aims to make it easy to build, update and
    analyze Ribasim models programmatically.

    The Ribasim QGIS plugin allows users to construct a model from scratch without programming.
    For specific tasks, like adding observed rainfall timeseries, it can be faster to use
    Python instead.

    One can also use Ribasim Python to build entire models from base data, such that your model
    setup is fully reproducible.

    For documentation please see the [examples](https://deltares.github.io/Ribasim/python/examples.html) and [API reference](https://deltares.github.io/Ribasim/python/reference/).
  license: MIT
  license_file: LICENSE
  doc_url: https://deltares.github.io/Ribasim/python/
  dev_url: https://github.com/Deltares/Ribasim/tree/main/python/ribasim

extra:
  recipe-maintainers:
    - Hofer-Julian
    - visr
    - Huite
