{% set name = "ribasim" %}
{% set version = "2024.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3da21ecadef168ac285fce01b6f4d307238463dabd1945233b5bd3584fa56612

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - geopandas
    - matplotlib-base
    - numpy
    - pandas
    - pandera >=0.20
    - pyarrow
    - pydantic ~=2.0
    - pyogrio
    - shapely >=2.0
    - tomli
    - tomli-w

test:
  imports:
    - ribasim
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://deltares.github.io/Ribasim/
  summary: Pre- and post-process Ribasim
  description: |
    The Ribasim Python package (named `ribasim`) aims to make it easy to build, update and
    analyze Ribasim models programmatically.

    The Ribasim QGIS plugin allows users to construct a model from scratch without programming.
    For specific tasks, like adding observed rainfall timeseries, it can be faster to use
    Python instead.

    One can also use Ribasim Python to build entire models from base data, such that your model
    setup is fully reproducible.

    For documentation please see the [examples](https://deltares.github.io/Ribasim/python/examples.html) and [API reference](https://deltares.github.io/Ribasim/python/reference/).
  license: MIT
  license_file: LICENSE
  doc_url: https://deltares.github.io/Ribasim/python/
  dev_url: https://github.com/Deltares/Ribasim/tree/main/python/ribasim

extra:
  recipe-maintainers:
    - SouthEndMusic
    - Hofer-Julian
    - visr
    - Huite
